### ISSUE TITLE
Create List component

### ISSUE THREAD

**Issue by ivanalejandro0** [Unixono/beautifulthings#12]
This screen is responsible of showing the list of items to the user.

Create the small components using storybook (#7).
For the `List` component set a route using `react-router` named `#/list`.

**Component:** `List`
This screen will show a `Header` (settings, logo, null), a `Welcome` message (if there are no items), a list of `ListItem` (if there are items), and an "Add" `Button` (#8).

**Component:** `ListItem`
This component represents a single item on the list of items. It will show the item date, text (trimmed) and an arrow (`ActionIcon`) to show the full item when clicked.

props:
- `date`
- `text`
- `onClick`

**Component:** `Welcome`
This is a simple component that just shows "What's your beautiful thing today?".

**Comment by fran-costa** [comment]
@chiiph, we should implement the ListItem as in the last UI design approach, isn't it?
