### ISSUE TITLE
Create SignUpScreen component

### ISSUE THREAD

**Issue by fran-costa** [Unixono/beautifulthings#25]
This screen is responsible of creating new accounts.

For the SignUpScreen component set a route using react-router named #/signup.

**Component:** SignUpScreen
- `Logo`: big
- `TextInput`: username
- `TextInput`: password
- `Button`: "Sign Up"

This screen will also include two modals:
- `LoadingModal`: to indicate when the signup process is going on
- `ButtonsModal`: to indicate the result of the signup process. It will have one button (`primaryButton`)

**Comment by fran-costa** [comment]
**IMPORTANT NOTE**

In the design, there isn't a _back_ button in this screen, but is needed... Where should be put it?

**Comment by chiiph** [comment]
> In the design, there isn't a back button in this screen, but is needed... Where should be put it?

Let's put a link underneath the "Sign Up" button that says "... or Sign In if you have an account" that takes you back.
