### ISSUE TITLE
Implement local notifications

### ISSUE THREAD

**Issue by chiiph** [Unixono/beautifulthings#6]
One of the main things for the app is the nagging to the user asking "What's your beautiful thing today?". At first I thought we needed to do that on the server, but it turns out we can do this on the client side.

Here's a cordova plugin that can be used, there might be better plugins, that's up to you to decide:

https://github.com/katzer/cordova-plugin-local-notifications

The app should periodically poll the preferences to see whether the nagging configuration changed (weekly or daily), and based on that it should setup local notifications to happen at 10pm (local time for the device) either every day or every Sunday.

The notification should show the app logo (non existent for now, but use a placeholder logo). And as mentioned before it should read: What's your beautiful thing today?

When the user taps on the notification it should take them directly to the beautiful thing creation pane, ready to write.

**Comment by fran-costa** [comment]
As far as I could read and test, it seems that this local notification plugin works quite good (at least in Android) and it has some good scheduling tools.

The problem that I found is that the notifications are displayed only when the app is running in background or even in foregroud, but if the app is killed or the system is rebooted, notification won't be displayed.

I searched and tested other plugins to found a workaround but without lucky yet...

**Comment by chiiph** [comment]
I'm probably not adding any new information here, but just in case:

I did a bit of searching, and it seems that as long as the plugin uses AlarmManager, it should work [1][2], do the plugins you tested use this? If it fails (which seems to be somewhat common, as you mentioned), it might be related to allowing the app to autostart, maybe you'll need another plugin for this [3].

iOS seems to be pretty straight forward, so the issue might be Android only, and it makes sense, since Android varies slightly depending the brand.

1: https://stackoverflow.com/questions/24327453/how-to-send-local-notification-android-when-app-is-closed?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
2: https://developer.android.com/training/scheduling/alarms
3: https://github.com/ToniKorin/cordova-plugin-autostart

**Comment by fran-costa** [comment]
Great, you're right! I'll take a look to Haggus plugin.
